In [12]:
import numpy as np
arr = np.array([[80,57,62,98,41,8],[77,85,98,59,40,2]])

In [13]:
print("The array demention",arr.ndim)

The array demention 2


In [14]:
print("Max number in the array",arr.max())

Max number in the array 98


In [15]:
print("Min number in the array",arr.min())

Min number in the array 2


In [16]:
print("Mean number in the array",arr.mean())

Mean number in the array 58.916666666666664


In [22]:
#shape of the array
print("Shape of the arr",np.shape(arr)) # row, colume

Shape of the arr (2, 6)


In [24]:
# reshare of a array
print(arr.reshape(3,4))

[[80 57 62 98]
 [41  8 77 85]
 [98 59 40  2]]


In [25]:
#2D to 1D a array
print(arr.reshape(-1))

[80 57 62 98 41  8 77 85 98 59 40  2]


In [29]:
#print by index
print(arr)
print("Print the element of 2nd row and 1st col",arr[1][0])

[[80 57 62 98 41  8]
 [77 85 98 59 40  2]]
Print the element of 2nd row and 1st col 77


In [31]:
arr2 = arr.reshape(-1) # reshape the array 2d to 1d
#slicing
print("element from index 3 to 5", arr2[3:6])

element from index 3 to 5 [98 41  8]


In [32]:
print("0 to 5 slicing: ", arr2[:6])

0 to 5 slicing:  [80 57 62 98 41  8]


In [35]:
print("Print the data type of array",arr2.dtype)

Print the data type of array int64


In [41]:
#copy
#view

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print("The orginal array", arr)
print("the copy array",x)

arr1 = np.array([1, 2, 3, 4, 5])
x = arr1.view()
arr[0] = 42
print("The orginal array", arr1)
print("the view array",x)

The orginal array [42  2  3  4  5]
the copy array [1 2 3 4 5]
The orginal array [1 2 3 4 5]
the view array [1 2 3 4 5]


In [38]:
#reshape 1d to 3d array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
#create a 5d array
n = np.array([7,8,9,5,6,12], ndmin= 5)
print(n)

[[[[[ 7  8  9  5  6 12]]]]]


In [43]:
#create a numpy array
arr1 = np.array([[1,2,3,4,5,6],[9,8,7,10,11,15]])

In [44]:
for i in arr1:
  for j in i:
    print(j)

1
2
3
4
5
6
9
8
7
10
11
15


In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

newarr = np.concatenate((arr1,arr2))
print(newarr)

[1 2 3 4 5 6]


In [48]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [49]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]
